### ISSUE TITLE
Please remove app from Google Play Store?

### ISSUE THREAD

**Issue by dandv** [guaka/meteor-phonegap#46]
Hi Kasper,

I was searching for "Meteor.js" in the Play Store, and found this outdated app:

https://play.google.com/store/apps/details?id=io.cordova.docsmeteorcom&hl=en

Any chance to pull it, since docs.meteor.com works great on mobile browsers?

Thanks,
Dan

**Comment by guaka** [comment]
thanks for the heads up, I removed it
